// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85idPi0NDUv3eUcFnu0RUw8oXcvaQTVg',
    appId: '1:738311747283:android:fa09c5953ba43db095c626',
    messagingSenderId: '738311747283',
    projectId: 'device-streaming-3e745aa8',
    storageBucket: 'device-streaming-3e745aa8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADhWR8dTvgdN5hJtdL7HMrQwGyHMCWUDE',
    appId: '1:738311747283:ios:ca31d63fbb54d09295c626',
    messagingSenderId: '738311747283',
    projectId: 'device-streaming-3e745aa8',
    storageBucket: 'device-streaming-3e745aa8.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiDummy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADhWR8dTvgdN5hJtdL7HMrQwGyHMCWUDE',
    appId: '1:738311747283:ios:ca31d63fbb54d09295c626',
    messagingSenderId: '738311747283',
    projectId: 'device-streaming-3e745aa8',
    storageBucket: 'device-streaming-3e745aa8.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiDummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5-pb5io4BldDMUtsGAqn1BMxomFSwI7w',
    appId: '1:738311747283:web:de6542300017bad795c626',
    messagingSenderId: '738311747283',
    projectId: 'device-streaming-3e745aa8',
    authDomain: 'device-streaming-3e745aa8.firebaseapp.com',
    storageBucket: 'device-streaming-3e745aa8.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5-pb5io4BldDMUtsGAqn1BMxomFSwI7w',
    appId: '1:738311747283:web:de6542300017bad795c626',
    messagingSenderId: '738311747283',
    projectId: 'device-streaming-3e745aa8',
    authDomain: 'device-streaming-3e745aa8.firebaseapp.com',
    storageBucket: 'device-streaming-3e745aa8.firebasestorage.app',
  );
}
