name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main

# Memberikan izin agar GitHub Actions bisa membuat branch khusus hosting
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web (Sesuaikan Base Href!)
        run: flutter build web --release --base-href="/aplikasi-dummy/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
